services:
  - type: web
    name: queuecare
    runtime: docker
    envVars:
      - key: QUEUECARE_DB_URL
        sync: false
      - key: QUEUECARE_DB_USERNAME
        sync: false
      - key: QUEUECARE_DB_PASSWORD
        sync: false

databases:
  - name: queuecare-db
    databaseName: queuecare
    plan: free
